// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaApi.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20240509224551_DataBase")]
    partial class DataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("API.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtorLivro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPublicacaoLivro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeLivro")
                        .HasColumnType("TEXT");

                    b.Property<string>("SinopseLivro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TabelaLivros");
                });
#pragma warning restore 612, 618
        }
    }
}
